apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  labels:
    app: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome:3.141.59
        volumeMounts:
          - name: selenium-storage
            mountPath: /data/selenium
        ports:
          - containerPort: 5900
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
          - name: NODE_MAX_SESSION
            value: "5"
          - name: NODE_MAX_INSTANCES
            value: "5"
        resources:
          limits:
            memory: "500Mi"
            cpu: ".5"
      volumes:
        - name: selenium-storage
          emptyDir: {}
